### ISSUE TITLE
AttributeError in wsgi.py

### ISSUE THREAD

**Issue by mtorrisi** [EGI-FCTF/occi-os#9]
Hi,

I'm facing a problem with my openstack and OCCI instance. My infrastructure is based on openstack Icehouse and in the last days I'm experimenting some issues with occi in particular having a look at `/var/log/nova/api.log` I saw the following error:
```
2017-01-19 16:01:45.823 20410 INFO nova.occiapi.wsgi.server [req-5094dd84-3cb0-4935-8c28-f6c2b67e1c49 799eca72e93d4670a4d981c42a220fe3 2d2eb7158a8940bdaad68afe6e9a138c] Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/eventlet/wsgi.py", line 389, in handle_one_response
    result = self.application(self.environ, start_response)
  File "/usr/lib/python2.6/site-packages/paste/urlmap.py", line 203, in __call__
    return app(environ, start_response)
  File "/usr/lib/python2.6/site-packages/keystoneclient/middleware/auth_token.py", line 679, in __call__
    return self.app(env, start_response)
  File "/usr/lib/python2.6/site-packages/webob/dec.py", line 144, in __call__
    return resp(environ, start_response)
  File "/usr/lib/python2.6/site-packages/occi_os_api/wsgi.py", line 152, in __call__
    self._refresh_os_mixins(extras)
  File "/usr/lib/python2.6/site-packages/occi_os_api/wsgi.py", line 170, in _refresh_os_mixins
    os_lst = [occify_terms(item['name']) for item in images]
  File "/usr/lib/python2.6/site-packages/occi_os_api/wsgi.py", line 273, in occify_terms
    term = term_name.strip().replace(' ', '_').replace('.', '-').lower()
AttributeError: 'NoneType' object has no attribute 'strip'
```

Do you have any suggestions about the previous problem?

Thanks in advace.

**Comment by enolfc** [comment]
Hi, 

OCCI-OS is no longer maintained by EGI, you should try to switch to [ooi]( https://launchpad.net/ooi), we are not producing any new releases of this code.

That said, it looks like you have images with no name in your site? One possible way to avoid the problem is to patch /usr/lib/python2.6/site-packages/occi_os_api/wsgi.py like this

```
$ diff -u wsgi.py.orig wsgi.py
--- wsgi.py.orig	2017-01-19 21:57:25.000000000 +0000
+++ wsgi.py	2017-01-19 21:58:42.000000000 +0000
@@ -271,5 +271,5 @@
     '''
     Occifies a term_name so that it is compliant with GFD 185.
     '''
-    term = term_name.strip().replace(' ', '_').replace('.', '-').lower()
+    term = str(term_name).strip().replace(' ', '_').replace('.', '-').lower()
     return term
```

**Comment by mtorrisi** [comment]
Thanks a lot @enolfc.

I found the image that didn't have a name, I gave it a name and everything work well again.

**Comment by mtorrisi** [comment]
Thanks a lot @enolfc.

I found the image that didn't have a name, I gave it a name and everything work well again.
